### ISSUE TITLE
doesn't handle localised timestamps

### ISSUE THREAD

**Issue by unhammer** [rksm/clj-org-analyzer#3]
I get
![må](https://user-images.githubusercontent.com/56868/63053247-a19f4700-bee1-11e9-8a30-c4d24ebc04d3.png)

from

```
*  Foo
  :LOGBOOK:
  CLOCK: [2018-03-26 må. 13:14]--[2018-03-26 må. 13:43] =>  0:29
  :END:
```

but it works fine if I change the `må.`'s to `Mon`. Emacs by default uses the system locale to get abbreviated weekdays, so you can get `Di` or `må.` [and so on](https://en.wikipedia.org/wiki/Renaming_of_Turkmen_months_and_days_of_week,_2002). I guess a timestamp should be parsable with something like `\[([0-9-]+) [^ ]+ ([0-9:]+)\]` (where \1 is date and \2 is time and the middle bit is ignored)

**Comment by hso** [comment]
This seems to be what was happening on #1

**Comment by rksm** [comment]
Language is hard :) Thanks for letting me know, will be fixed.

**Comment by hso** [comment]
Fixed in PR #6, if everything looks OK you can just merge it (and that will auto close the relevant issues) :)

**Comment by unhammer** [comment]
Should this have been fixed in the 0.3.3 jar? I'm still getting the same output.

**Comment by unhammer** [comment]
This is still not working in 0.3.4 :-( 

Was there some regression, should I open a new issue?

**Comment by rksm** [comment]
Sorry for that, I'll investigate.

**Comment by rksm** [comment]
Apologies, this should be fixed for real now. There was one additional regexp to find CLOCKs that needed a change. The release is here: https://github.com/rksm/clj-org-analyzer/releases/tag/0.3.5

**Comment by unhammer** [comment]
Sweet, it works on my giant work.org file now =D Thanks for the quick fix :-)
